// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Bfcode_ButtonInput","status":true,"description":"全按鍵，解決您按鍵不夠的煩惱","parameters":{}},
{"name":"Bfcode_MainMenu","status":true,"description":"","parameters":{}},
{"name":"Bfcode_Login","status":true,"description":"","parameters":{}},
{"name":"AXY_TitleMenu","status":true,"description":"v1.00 Display Multiple Menu in Title Screen.","parameters":{"DisplayJumpToMap":"false","JumpToMapText":"","JumpToMapId":"","JumpToMapSwitchId":"","DisplayExit":"true","ExitText":"退出游戏","MaxCols":"4","WindowWidth":"800","X":"(Graphics.boxWidth - this.width) / 2","Y":"Graphics.boxHeight - this.height - 96","WindowSkin":"Window","Align":"center","TextColor":"white"}},
{"name":"partice","status":true,"description":"标题粒子效果","parameters":{"file":"particle","num":"20","xSpeed":"1","ySpeed":"1","rotation":"0.01"}}
];
